name: post_to_announcement
on: [push]
jobs:
  push_to_update:
    runs-on: ubuntu-latest
    steps:
      - name: Make sure CURL is installed
        run: sudo apt install curl
      - name: Post changes to Announcement
        run: curl -x POST https://discord.com/api/webhooks/1222639782115545189/nD00Hvi2Gy0SrM1L3uW4dVnQlDweJurTWZmknqd19Lcgba6tdHGg_Svdh7Fsy3Fm63xf --json '{ "content": "TESTE"}'
